/**
 * Export centralisé des types
 *
 * Ce fichier réexporte tous les types pour faciliter les imports.
 * Préférez importer depuis les modules spécifiques pour une meilleure organisation.
 */

// Types Core
export * from './core';

// Types partagés
export * from './shared';

// Types HR
export * from './hr';

// Types Inventory
// Note: Category and PaginatedResponse from inventory are not re-exported to avoid conflicts
// Use them directly from './inventory' if needed, or use the ones from './core' and './shared'
export type {
  // Category types - use InventoryCategory to avoid conflict with CoreCategory
  Category as InventoryCategory,
  CategoryCreate,
  CategoryUpdate,
  CategoryTree,
  CategoryPerformance,
  CategoryStockReport,
  CategoryRevenue,
  // PaginatedResponse - use InventoryPaginatedResponse to avoid conflict
  PaginatedResponse as InventoryPaginatedResponse,
  // All other inventory types
  ProductUnit,
  MovementType,
  OrderStatus,
  StockCountStatus,
  AlertType,
  AlertSeverity,
  Warehouse,
  WarehouseCreate,
  WarehouseUpdate,
  WarehouseStats,
  Supplier,
  SupplierCreate,
  SupplierUpdate,
  Stock,
  StockCreate,
  StockUpdate,
  Product,
  ProductCreate,
  ProductUpdate,
  ProductList,
  Movement,
  MovementCreate,
  MovementUpdate,
  OrderItem,
  OrderItemCreate,
  Order,
  OrderCreate,
  OrderUpdate,
  OrderList,
  StockCountItem,
  StockCountItemCreate,
  StockCount,
  StockCountCreate,
  StockCountUpdate,
  Alert,
  AlertCreate,
  AlertUpdate,
  InventoryStats,
  ABCDistribution,
  PaymentMethodBreakdown,
  ExpenseCategoryBreakdown,
  RecentAlert,
  SalesTrendItem,
  TopSellingProduct,
  LowStockProduct,
  MovementsSummary30d,
  TopProduct,
  WarehouseStockReport,
  MovementTypeDetail,
  DailyMovementHistory,
  MovementSummary,
  MovementHistoryResponse,
  LowRotationProduct,
  LowRotationProductsResponse,
  StockCountReportItem,
  StockCountsSummary,
  StockCountsSummaryResponse,
  FinancialAnalysisSummary,
  PaymentMethodDistribution,
  DailySales,
  FinancialAnalysisResponse,
  ABCProduct,
  ABCAnalysisDistribution,
  ABCAnalysisResponse,
  CreditByCustomer,
  RecentCredit,
  CreditsReportSummary,
  CreditsReportResponse,
  SalesPerformanceSummary,
  SalesByWeekday,
  SalesByHour,
  TopProductSold,
  SalesPerformanceResponse,
  InventoryApiError,
  // Sales types
  PaymentStatus,
  PaymentMethod,
  DiscountType,
  ProformaStatus,
  DeliveryNoteStatus,
  CreditSaleStatus,
  Customer,
  CustomerCreate,
  CustomerUpdate,
  SaleItem,
  SaleItemCreate,
  Sale,
  SaleCreate,
  SaleUpdate,
  SaleList,
  Payment,
  PaymentCreate,
  ExpenseCategory,
  ExpenseCategoryCreate,
  Expense,
  ExpenseCreate,
  ExpenseUpdate,
  ExpenseSummary,
  ProformaItem,
  ProformaItemCreate,
  ProformaInvoice,
  ProformaCreate,
  ProformaUpdate,
  PurchaseOrderItem,
  PurchaseOrderItemCreate,
  PurchaseOrder,
  PurchaseOrderCreate,
  DeliveryNoteItem,
  DeliveryNoteItemCreate,
  DeliveryNote,
  DeliveryNoteCreate,
  CreditSale,
  CreditSaleSummary,
  CreditPayment,
  CreditPaymentCreate,
} from './inventory';

// Types Notifications
export * from './notifications';

